import { FadeTheme } from './types';

export const themes: FadeTheme[] = [
  {
    id: 'romantic-roses',
    name: 'Eternal Rose',
    description: 'Crimson petals drift through the air',
    background: '#0d0508',
    palette: {
      primary: '#e8184f',
      secondary: '#c41230',
      accent: '#ff6b8a',
    },
    themeEngine: {
      particleDensity: 'medium',
      motionBehavior: 'fall',
      backgroundLayer: 'gradient',
      emotionalIntensity: 'deep',
      particleShape: 'petal',
    },
    pacing: {
      introDelay: 1.2,
      typingSpeed: 80,
      pauseBetweenSteps: 1500,
    },
    previewGradient: 'linear-gradient(135deg, #0d0508 0%, #2d0a15 50%, #1a0510 100%)',
    signOff: 'with love,',
    brandFooter: 'lovethatneverfades',
  },
  {
    id: 'magic-stars',
    name: 'Starfall',
    description: 'A constellation written just for you',
    background: '#04050f',
    palette: {
      primary: '#a78bfa',
      secondary: '#7c3aed',
      accent: '#c4b5fd',
    },
    themeEngine: {
      particleDensity: 'high',
      motionBehavior: 'drift',
      backgroundLayer: 'animated-gradient',
      emotionalIntensity: 'soft',
      particleShape: 'star',
    },
    pacing: {
      introDelay: 1.0,
      typingSpeed: 70,
      pauseBetweenSteps: 1200,
    },
    previewGradient: 'linear-gradient(135deg, #04050f 0%, #0d0b2a 50%, #080516 100%)',
    signOff: 'yours under the stars,',
    brandFooter: 'constellationsoflove',
  },
  {
    id: 'love-balloons',
    name: 'Float Away',
    description: 'Let your heart rise above',
    background: '#0a0a12',
    palette: {
      primary: '#f472b6',
      secondary: '#db2777',
      accent: '#fbbf24',
    },
    themeEngine: {
      particleDensity: 'low',
      motionBehavior: 'float',
      backgroundLayer: 'animated-gradient',
      emotionalIntensity: 'medium',
      particleShape: 'balloon',
    },
    pacing: {
      introDelay: 1.4,
      typingSpeed: 90,
      pauseBetweenSteps: 1800,
    },
    previewGradient: 'linear-gradient(135deg, #0a0a12 0%, #1a0a1a 50%, #120a1a 100%)',
    signOff: 'floating with love,',
    brandFooter: 'risingtogether',
  },
  {
    id: 'sunset-glow',
    name: 'Ember Dusk',
    description: 'Warm embers at the edge of night',
    background: '#0f0700',
    palette: {
      primary: '#f97316',
      secondary: '#dc2626',
      accent: '#fbbf24',
    },
    themeEngine: {
      particleDensity: 'medium',
      motionBehavior: 'pulse',
      backgroundLayer: 'gradient',
      emotionalIntensity: 'deep',
      particleShape: 'ember',
    },
    pacing: {
      introDelay: 1.3,
      typingSpeed: 85,
      pauseBetweenSteps: 1400,
    },
    previewGradient: 'linear-gradient(135deg, #0f0700 0%, #1f0f00 50%, #150800 100%)',
    signOff: 'with warm thoughts,',
    brandFooter: 'embersinthedusk',
  },
  {
    id: 'galaxy-romance',
    name: 'Infinite',
    description: 'Lost in the cosmos, found in you',
    background: '#020408',
    palette: {
      primary: '#38bdf8',
      secondary: '#0ea5e9',
      accent: '#e879f9',
    },
    themeEngine: {
      particleDensity: 'high',
      motionBehavior: 'drift',
      backgroundLayer: 'animated-gradient',
      emotionalIntensity: 'deep',
      particleShape: 'circle',
    },
    pacing: {
      introDelay: 1.1,
      typingSpeed: 75,
      pauseBetweenSteps: 1300,
    },
    previewGradient: 'linear-gradient(135deg, #020408 0%, #050d1a 50%, #080210 100%)',
    signOff: 'infinitely yours,',
    brandFooter: 'loveinfinite',
  },
  {
    id: 'teddy-love',
    name: 'Teddy Love',
    description: 'Soft bears tumbling through a warm embrace',
    background: '#0d0805',
    palette: {
      primary:   '#c4874a',
      secondary: '#8b5e34',
      accent:    '#f4c0a0',
    },
    themeEngine: {
      particleDensity:    'medium',
      motionBehavior:     'fall',
      backgroundLayer:    'gradient',
      emotionalIntensity: 'soft',
      particleShape:      'bear',
    },
    pacing: {
      introDelay:        1.2,
      typingSpeed:       80,
      pauseBetweenSteps: 1500,
    },
    previewGradient: 'linear-gradient(135deg, #0d0805 0%, #1f1008 50%, #160b05 100%)',
    signOff: 'with bear hugs,',
    brandFooter: 'cuddlesthemoment',
  },
  {
    id: 'love-emojis',
    name: 'Love Language',
    description: 'Every feeling rising as a tiny symbol',
    background: '#0d0510',
    palette: {
      primary:   '#f43f8e',
      secondary: '#c026a8',
      accent:    '#fb7185',
    },
    themeEngine: {
      particleDensity:    'medium',
      motionBehavior:     'float',
      backgroundLayer:    'animated-gradient',
      emotionalIntensity: 'medium',
      particleShape:      'emoji',
    },
    pacing: {
      introDelay:        1.1,
      typingSpeed:       78,
      pauseBetweenSteps: 1400,
    },
    previewGradient: 'linear-gradient(135deg, #0d0510 0%, #200828 50%, #160510 100%)',
    signOff: 'with all my heart,',
    brandFooter: 'ourlovelanguage',
  },
  {
    id: 'pink-petals',
    name: 'Blush Storm',
    description: 'A blizzard of soft pink petals',
    background: '#0d0509',
    palette: {
      primary:   '#f9a8d4',
      secondary: '#f472b6',
      accent:    '#fce7f3',
    },
    themeEngine: {
      particleDensity:    'high',
      motionBehavior:     'fall',
      backgroundLayer:    'gradient',
      emotionalIntensity: 'medium',
      particleShape:      'petal',
    },
    pacing: {
      introDelay:        1.0,
      typingSpeed:       75,
      pauseBetweenSteps: 1300,
    },
    previewGradient: 'linear-gradient(135deg, #0d0509 0%, #250a18 50%, #1a0610 100%)',
    signOff: 'softly yours,',
    brandFooter: 'softblushdreams',
  },
  {
    id: 'white-petals',
    name: 'Ivory Dream',
    description: 'Pure white petals in silent cascade',
    background: '#07070a',
    palette: {
      primary:   '#f1f5f9',
      secondary: '#cbd5e1',
      accent:    '#e2e8f0',
    },
    themeEngine: {
      particleDensity:    'medium',
      motionBehavior:     'fall',
      backgroundLayer:    'gradient',
      emotionalIntensity: 'soft',
      particleShape:      'petal',
    },
    pacing: {
      introDelay:        1.3,
      typingSpeed:       85,
      pauseBetweenSteps: 1600,
    },
    previewGradient: 'linear-gradient(135deg, #07070a 0%, #10101a 50%, #0c0c14 100%)',
    signOff: 'with pure affection,',
    brandFooter: 'pureandserene',
  },
  {
    id: 'golden-petals',
    name: 'Golden Hour',
    description: 'Warm gold petals catching the last light',
    background: '#0a0800',
    palette: {
      primary:   '#f59e0b',
      secondary: '#d97706',
      accent:    '#fde68a',
    },
    themeEngine: {
      particleDensity:    'medium',
      motionBehavior:     'fall',
      backgroundLayer:    'gradient',
      emotionalIntensity: 'medium',
      particleShape:      'petal',
    },
    pacing: {
      introDelay:        1.2,
      typingSpeed:       82,
      pauseBetweenSteps: 1500,
    },
    previewGradient: 'linear-gradient(135deg, #0a0800 0%, #1a1200 50%, #120e00 100%)',
    signOff: 'wishing you golden days,',
    brandFooter: 'goldenhourglow',
  },
  {
    id: 'money-flow',
    name: 'Neon Wealth',
    description: 'Holographic bills rain through a neon night',
    background: '#030206',
    palette: {
      primary: '#00e5ff',   // Electric Cyan
      secondary: '#00ffcc', // Neon Mint
      accent: '#ffd700',    // Brushed Gold
    },
    themeEngine: {
      particleDensity: 'high',
      motionBehavior: 'fall',
      backgroundLayer: 'animated-gradient',
      emotionalIntensity: 'deep',
      particleShape: 'money',
    },
    pacing: {
      introDelay: 1.2,
      typingSpeed: 80,
      pauseBetweenSteps: 1500,
    },
    previewGradient: 'linear-gradient(135deg, #030206 0%, #0b0f19 50%, #05040a 100%)',
    signOff: 'to your abundance & success,',
    brandFooter: 'limitlessabundance',
  },
  {
    id: 'birthday-celebration',
    name: 'Birthday Bash',
    description: 'Vibrant balloons rise through a festive night sky, each carrying a birthday wish',
    background: '#030010',
    palette: {
      primary: '#ff4daa',    // Electric Coral Pink
      secondary: '#ffe135',  // Vivid Gold
      accent: '#00e5ff',     // Neon Cyan
    },
    themeEngine: {
      particleDensity: 'high',
      motionBehavior: 'float',
      backgroundLayer: 'animated-gradient',
      emotionalIntensity: 'deep',
      particleShape: 'birthday-balloon',
    },
    pacing: {
      introDelay: 1.0,
      typingSpeed: 72,
      pauseBetweenSteps: 1200,
    },
    previewGradient: 'linear-gradient(135deg, #030010 0%, #16043a 50%, #08021a 100%)',
    signOff: 'with birthday love,',
    brandFooter: 'wishesthatneverfade',
  },
];

export const getTheme = (id: string): FadeTheme =>
  themes.find((t) => t.id === id) ?? themes[0];
